-- ow_con08a gates — GENERATED by tools/owworld, do not edit by hand.
-- Regenerate: go run ./tools/owgates <maps>; go run ./tools/owworld

local Nox = require("Nox.Map.Script.v0")

local GATES = {
    { x = 5440, y = 3876, dest = "ow_con03a:@522,522", name = "con03a" },
    { x = 1108, y = 3627, dest = "ow_con07h:@2263,1632", name = "con07h" },
    { x = 3979, y = 1472, dest = "ow_con08b:@3781,4584", name = "con08b" },
    { x = 1018, y = 3627, dest = "ow_con08e:@1097,3264", name = "con08e" },
    { x = 632, y = 1920, dest = "ow_con09a:@5506,5610", name = "con09a" },
}

local NEAR = 50   -- stepping this close to a gate travels
local AWAY = 130  -- a gate arms once the player has been this far from it
local HINT = 250  -- distance at which the road hint prints

local armed = {}
local hinted = {}
local fired = false

function OnFrame()
    if fired then
        return
    end
    local p = Nox.Players.host
    if p == nil then
        return
    end
    local x, y = p:Pos()
    if x == 0 and y == 0 then
        return
    end
    for i, g in ipairs(GATES) do
        local dx, dy = x - g.x, y - g.y
        local d2 = dx * dx + dy * dy
        if not armed[i] then
            -- gates start disarmed so arriving on one can't bounce you back
            if d2 > AWAY * AWAY then
                armed[i] = true
            end
        else
            if not hinted[i] and d2 < HINT * HINT then
                hinted[i] = true
                p:Print("[Openworld] The road to " .. g.name .. " lies here.")
            end
            if d2 < NEAR * NEAR then
                fired = true
                p:Print("[Openworld] Travelling to " .. g.name .. "...")
                Nox.LoadMap(g.dest)
                return
            end
        end
    end
end
