-- ow_con05a gates — GENERATED by tools/owworld, do not edit by hand.
-- Regenerate: go run ./tools/owgates <maps>; go run ./tools/owworld

local Nox = require("Nox.Map.Script.v0")

local FACTION = "conjurer" -- this zone's campaign faction

local GATES = {
    { x = 1522, y = 3481, dest = "ow_con04c:@4350,5486", name = "con04c" },
    { x = 3097, y = 147, dest = "ow_con05b:@384,1418", name = "con05b" },
    { x = 3406, y = 513, dest = "ow_con06a:@5187,2516", name = "con06a" },
}

local NEAR = 50   -- stepping this close to a gate travels
local AWAY = 130  -- a gate arms once the player has been this far from it
local HINT = 250  -- distance at which the road hint prints

local armed = {}
local hinted = {}
local fired = false
local factionsSet = false

-- Put the player on their class team and this zone's NPCs on the zone's
-- faction team, so your own faction is friendly and other factions are
-- hostile (same team = allied; see engine IsEnemyTo).
local function setFactions()
    Nox.SetMapUnitsTeam(FACTION)
    local class = Nox.HostClass()
    if class ~= "" then
        Nox.SetHostTeam(class)
    else
        -- unknown class: ally with this zone so the player isn't mobbed
        Nox.SetHostTeam(FACTION)
    end
end

function OnFrame()
    local p = Nox.Players.host
    if p == nil then
        return
    end
    if not factionsSet then
        factionsSet = true
        setFactions()
    end
    if fired then
        return
    end
    local x, y = p:Pos()
    if x == 0 and y == 0 then
        return
    end
    for i, g in ipairs(GATES) do
        local dx, dy = x - g.x, y - g.y
        local d2 = dx * dx + dy * dy
        if not armed[i] then
            -- gates start disarmed so arriving on one can't bounce you back
            if d2 > AWAY * AWAY then
                armed[i] = true
            end
        else
            if not hinted[i] and d2 < HINT * HINT then
                hinted[i] = true
                p:Print("[Openworld] The road to " .. g.name .. " lies here.")
            end
            if d2 < NEAR * NEAR then
                fired = true
                p:Print("[Openworld] Travelling to " .. g.name .. "...")
                Nox.LoadMap(g.dest)
                return
            end
        end
    end
end
