-- ow_war08a gates — GENERATED by tools/owworld, do not edit by hand.
-- Regenerate: go run ./tools/owgates <maps>; go run ./tools/owworld

local Nox = require("Nox.Map.Script.v0")

local FACTION = "warrior" -- this zone's campaign faction

local GATES = {
    { x = 5440, y = 3876, dest = "ow_con03a:@391,414", name = "con03a" },
    { x = 1087, y = 3621, dest = "ow_war07g:@2340,1697", name = "war07g" },
    { x = 3972, y = 1479, dest = "ow_war08b:@3781,4584", name = "war08b" },
    { x = 997, y = 3621, dest = "ow_war08e:@1097,3264", name = "war08e" },
    { x = 1991, y = 5023, dest = "ow_war09a:@5505,5613", name = "war09a" },
}

local NEAR = 50   -- stepping this close to a gate travels
local AWAY = 130  -- a gate arms once the player has been this far from it
local HINT = 250  -- distance at which the road hint prints

local armed = {}
local hinted = {}
local fired = false
local factionsSet = false

-- Put the player on their class team and this zone's NPCs on the zone's
-- faction team, so your own faction is friendly and other factions are
-- hostile (same team = allied; see engine IsEnemyTo).
local function setFactions()
    Nox.SetMapUnitsTeam(FACTION)
    local class = Nox.HostClass()
    if class ~= "" then
        Nox.SetHostTeam(class)
    else
        -- unknown class: ally with this zone so the player isn't mobbed
        Nox.SetHostTeam(FACTION)
    end
end

function OnFrame()
    local p = Nox.Players.host
    if p == nil then
        return
    end
    if not factionsSet then
        factionsSet = true
        setFactions()
    end
    if fired then
        return
    end
    local x, y = p:Pos()
    if x == 0 and y == 0 then
        return
    end
    for i, g in ipairs(GATES) do
        local dx, dy = x - g.x, y - g.y
        local d2 = dx * dx + dy * dy
        if not armed[i] then
            -- gates start disarmed so arriving on one can't bounce you back
            if d2 > AWAY * AWAY then
                armed[i] = true
            end
        else
            if not hinted[i] and d2 < HINT * HINT then
                hinted[i] = true
                p:Print("[Openworld] The road to " .. g.name .. " lies here.")
            end
            if d2 < NEAR * NEAR then
                fired = true
                p:Print("[Openworld] Travelling to " .. g.name .. "...")
                Nox.LoadMap(g.dest)
                return
            end
        end
    end
end
