-- ow_con03a gates — GENERATED by tools/owworld, do not edit by hand.
-- Regenerate: go run ./tools/owgates <maps>; go run ./tools/owworld

local Nox = require("Nox.Map.Script.v0")

local GATES = {
    { x = 345, y = 368, dest = "ow_con02a:@5440,3876", name = "con02a" },
    { x = 231, y = 4646, dest = "ow_con03b:@5428,1748", name = "con03b" },
    { x = 651, y = 3421, dest = "ow_con04a:@4576,1861", name = "con04a" },
    { x = 481, y = 414, dest = "ow_con08a:@5440,3876", name = "con08a" },
    { x = 571, y = 414, dest = "ow_war08a:@5440,3876", name = "war08a" },
    { x = 391, y = 414, dest = "ow_wiz08a:@5440,3876", name = "wiz08a" },
}

local NEAR = 50   -- stepping this close to a gate travels
local AWAY = 130  -- a gate arms once the player has been this far from it
local HINT = 250  -- distance at which the road hint prints

local armed = {}
local hinted = {}
local fired = false

function OnFrame()
    if fired then
        return
    end
    local p = Nox.Players.host
    if p == nil then
        return
    end
    local x, y = p:Pos()
    if x == 0 and y == 0 then
        return
    end
    for i, g in ipairs(GATES) do
        local dx, dy = x - g.x, y - g.y
        local d2 = dx * dx + dy * dy
        if not armed[i] then
            -- gates start disarmed so arriving on one can't bounce you back
            if d2 > AWAY * AWAY then
                armed[i] = true
            end
        else
            if not hinted[i] and d2 < HINT * HINT then
                hinted[i] = true
                p:Print("[Openworld] The road to " .. g.name .. " lies here.")
            end
            if d2 < NEAR * NEAR then
                fired = true
                p:Print("[Openworld] Travelling to " .. g.name .. "...")
                Nox.LoadMap(g.dest)
                return
            end
        end
    end
end
