-- ow_wiz05a gates — GENERATED by tools/owworld, do not edit by hand.
-- Regenerate: go run ./tools/owgates <maps>; go run ./tools/owworld

local Nox = require("Nox.Map.Script.v0")

local GATES = {
    { x = 1523, y = 3480, dest = "ow_wiz04c:@4355,5485", name = "wiz04c" },
    { x = 3093, y = 149, dest = "ow_wiz05b:@383,1421", name = "wiz05b" },
    { x = 3957, y = 1050, dest = "ow_wiz06a:@4036,4576", name = "wiz06a" },
}

local NEAR = 50   -- stepping this close to a gate travels
local AWAY = 130  -- a gate arms once the player has been this far from it
local HINT = 250  -- distance at which the road hint prints

local armed = {}
local hinted = {}
local fired = false

function OnFrame()
    if fired then
        return
    end
    local p = Nox.Players.host
    if p == nil then
        return
    end
    local x, y = p:Pos()
    if x == 0 and y == 0 then
        return
    end
    for i, g in ipairs(GATES) do
        local dx, dy = x - g.x, y - g.y
        local d2 = dx * dx + dy * dy
        if not armed[i] then
            -- gates start disarmed so arriving on one can't bounce you back
            if d2 > AWAY * AWAY then
                armed[i] = true
            end
        else
            if not hinted[i] and d2 < HINT * HINT then
                hinted[i] = true
                p:Print("[Openworld] The road to " .. g.name .. " lies here.")
            end
            if d2 < NEAR * NEAR then
                fired = true
                p:Print("[Openworld] Travelling to " .. g.name .. "...")
                Nox.LoadMap(g.dest)
                return
            end
        end
    end
end
